{{ $component := .Values.components.esrProxy }}
{{ if $component.enabled }}
{{ $config := $component.configuration }}
{{ $kafka := .Values.kafka}}
{{ $bootstrap := $kafka.bootstrapServers |
          default (printf "%s.%s:%s" $kafka.fullnameOverride .Values.namespace $kafka.port) }}
{{ $image := eq .Values.license.installationType "SELF_HOSTED" | ternary
(printf "%s/%s/%s/%s:%s" .Values.registry.url .Values.registry.base.prefix .Values.registry.base.path $component.image.name $component.image.version)
(printf "%s/%s:%s" .Values.registry.awsMarketplaceUrl (regexReplaceAll ".+/(.+)$" $component.image.name "${1}") $component.image.version)
}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: esr-proxy
  namespace: {{ .Values.namespace }}
  labels:
    strmprivacy.io/app: esr-proxy
spec:
  replicas: {{ $component.replicas }}
  selector:
    matchLabels:
      strmprivacy.io/app: esr-proxy
  template:
    metadata:
      labels:
        strmprivacy.io/app: esr-proxy
    spec:
      {{ if eq .Values.license.installationType "SELF_HOSTED" }}
      imagePullSecrets:
        - name: strmprivacy-docker-registry
      {{ end }}
      containers:
        - name: esr-proxy
          image: {{ $image }}
          env:
            - name: APP_BOOTSTRAP_SERVERS
              value: {{ $bootstrap }}
            {{ include "installationEnvironmentVariables" .}}
            {{ if eq .Values.license.installationType "SELF_HOSTED" }}
            {{ include "selfHostedEnvironmentVariables" .}}
            {{ end }}

{{ end }}
