{{ $component := .Values.components.esrProxy }}
{{ if $component.enabled }}

{{ $name := $component.name }}
{{ $data := dict "values" .Values "component" $component }}
{{ $image := include "image" $data }}
{{ $bootstrap := include "kafkaBootstrap" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: esr-proxy
  namespace: {{ .Values.namespace }}
  labels:
    strmprivacy.io/app: esr-proxy
spec:
  replicas: {{ $component.replicas }}
  selector:
    matchLabels:
      strmprivacy.io/app: esr-proxy
  template:
    metadata:
      labels:
        strmprivacy.io/app: esr-proxy
    spec:
      {{ if eq .Values.license.installationType "SELF_HOSTED" }}
      imagePullSecrets:
        - name: strmprivacy-docker-registry
      {{ end }}
      containers:
        - name: esr-proxy
          image: {{ $image }}
          env:
            - name: APP_BOOTSTRAP_SERVERS
              value: {{ $bootstrap }}
            {{ include "kafkaSecurityEnvironmentVars" .}}
            {{- include "kafkaCredentialsEnvironmentVars" $data -}}
            {{ include "installationEnvironmentVariables" .}}
            {{ if eq .Values.license.installationType "SELF_HOSTED" }}
            {{ include "selfHostedEnvironmentVariables" .}}
            {{ end }}
          volumeMounts:
          {{- template "clientTruststoreVolumeMount" . }}
      volumes:
        {{- template "clientTruststoreVolume" . }}
  {{ end }}
