{{ $component := .Values.components.eventGateway }}
{{ if and $component.enabled .Values.services.clusterIp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: confluent-schema-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    strmprivacy.io/app: confluent-schema-proxy
    strmprivacy.io/version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http

  selector:
    strmprivacy.io/app: confluent-schema-proxy
{{ end }}
