{{ $component := .Values.components.eventGateway }}
{{ if $component.enabled and .Values.services.cluster_ip.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: confluent-schema-proxy
  namespace: {{ .Values.namespace }}
  labels:
    strmprivacy.io/app: confluent-schema-proxy
    strmprivacy.io/version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http

  selector:
    strmprivacy.io/app: confluent-schema-proxy
{{ end }}
