{{ $component := .Values.components.batchJobAgent }}
{{ if and $component.enabled (not .Values.postgresql.enabled) }}
# create a secret with the password from the value in the batchJobAgent section

apiVersion: v1
data:
  postgres-password: {{ $component.configuration.postgres.password | b64enc }}
kind: Secret
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  annotations:
    create-by: bart
type: Opaque

{{ end }}
