{{ $component := .Values.components.batchJobAgent }}
{{ if and $component.enabled (not .Values.postgresql.enabled) $component.configuration.postgres.password }}
# Create a secret with the postgres password, but only when using a custom postgres DB and if a password was provided (otherwise a custom secret must already exist)

apiVersion: v1
data:
  postgres-password: {{ $component.configuration.postgres.password | b64enc }}
kind: Secret
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}

{{ end }}
