{{ $component := .Values.components.batchExportersAgent }}
{{ if $component.enabled }}

{{ $name := $component.name }}
{{ $config := $component.configuration }}
{{ $kafka := .Values.kafka}}
{{ $bootstrap := $kafka.bootstrapServers |
          default (printf "%s-headless.%s.svc.cluster.local:%s" $kafka.fullnameOverride .Values.namespace $kafka.port) }}
{{ $image := eq .Values.license.installationType "SELF_HOSTED" | ternary
(printf "%s/%s/%s/%s:%s" .Values.registry.url .Values.registry.base.prefix .Values.registry.base.path $component.image.name $component.image.version)
(printf "%s/%s:%s" .Values.registry.awsMarketplaceUrl (regexReplaceAll ".+/(.+)$" $component.image.name "${1}") $component.image.version)
}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      strmprivacy.io/app: {{$name}}
  template:
    metadata:
      labels:
        strmprivacy.io/app: {{$name}}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{$name}}
      {{ if eq .Values.license.installationType "SELF_HOSTED" }}
      imagePullSecrets:
        - name: strmprivacy-docker-registry
      {{ end }}
      containers:
        - name: agent
          env:
          {{ include "kafkaSecurityEnvironmentVars" .}}
            - name: STRM_KAFKASEC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{$name}}
                  key: kafka.user
            - name: STRM_KAFKASEC_PW
              valueFrom:
                secretKeyRef:
                  name: {{$name}}
                  key: kafka.password
          {{ include "installationEnvironmentVariables"  . }}
            - name: APP_NAMESPACE
              value: {{ .Values.namespace }}
            - name: STRM_BOOTSTRAP_SERVERS
              value: {{ $bootstrap }}
          {{ if eq .Values.license.installationType "SELF_HOSTED" }}
          {{ include "selfHostedEnvironmentVariables" .}}
          {{ end }}
          image: {{ $image }}
          {{ if .Values.kafkaSecurityConfig.enabled }}
          volumeMounts:
            - mountPath: /var/truststore
              name: client-truststore
          {{ end }}
      volumes:
        {{ if .Values.kafkaSecurityConfig.enabled }}
        - name: client-truststore
          secret:
            secretName: {{ .Values.kafkaSecurityConfig.sslTruststoreSecretName }}
            optional: false
        {{ end }}



{{ end }}
