{{ $component := .Values.components.batchExportersAgent }}
{{ if $component.enabled }}

{{ $name := $component.name }}
{{ $bootstrap := include "kafkaBootstrap" . }}
{{ $data := dict "values" .Values "component" $component }}
{{ $image := include "image" $data }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      strmprivacy.io/app: {{$name}}
  template:
    metadata:
      labels:
        strmprivacy.io/app: {{$name}}
    spec:
      serviceAccountName: {{$name}}
      {{ if eq .Values.license.installationType "SELF_HOSTED" }}
      imagePullSecrets:
        - name: strmprivacy-docker-registry
      {{ end }}
      containers:
        - name: agent
          env:
          {{ include "kafkaSecurityEnvironmentVars" .}}
          {{- include "kafkaCredentialsEnvironmentVars" $data -}}
          {{ include "installationEnvironmentVariables"  . }}
            - name: APP_NAMESPACE
              value: {{ .Values.namespace }}
            - name: STRM_BOOTSTRAP_SERVERS
              value: {{ $bootstrap }}
          {{ if eq .Values.license.installationType "SELF_HOSTED" }}
          {{ include "selfHostedEnvironmentVariables" .}}
          {{ end }}
          image: {{ $image }}
          volumeMounts:
          {{- template "clientTruststoreVolumeMount" . }}
      volumes:
        {{- template "clientTruststoreVolume" . }}
{{ end }}
