{{ $component := .Values.components.dataConnectorAgent }}
{{ if $component.enabled }}

{{ $name := $component.name }}
{{ $data := dict "values" .Values "component" $component }}
{{ $image := include "image" $data }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      serviceAccountName: {{ $name }}
      {{ if eq .Values.license.installationType "SELF_HOSTED" }}
      imagePullSecrets:
        - name: strmprivacy-docker-registry
      {{ end }}
      containers:
        - name: agent
          image: {{ $image }}
          env:
            {{ include "installationEnvironmentVariables" . }}
            {{ if eq .Values.license.installationType "SELF_HOSTED" }}
            {{ include "selfHostedEnvironmentVariables" .}}
            {{ end }}
            - name: APP_NAMESPACE
              value: {{ .Values.namespace }}
{{ end }}
