{{ $component := .Values.components.dataConnectorAgent }}
{{ if $component.enabled }}

{{ $name := $component.name }}
{{ $config := $component.configuration }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if and (contains "AWS_" .Values.license.installationType) (((.Values.marketplace).aws).serviceAccountRoleArn) }}
    eks.amazonaws.com/role-arn: "{{ ((.Values.marketplace).aws).serviceAccountRoleArn }}"
    {{- end }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - secrets
    verbs:
      - list
      - create
      - update
      - patch
      - get
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $name }}-customers"
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{.Release.Namespace}}

{{ end }}
