{{ $component := .Values.components.decrypterConfig }}
{{ if $component.enabled }}

{{ $kafka := .Values.kafka}}
{{ $bootstrap := $component.kafkaBootstrapServers |
          default (printf "%s.%s:%s" $kafka.fullnameOverride .Values.namespace $kafka.port) }}
{{ $redis := $component.redisHost |
      default (printf "%s-headless.%s" .Values.redis.fullnameOverride .Values.namespace) }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: decrypter-config
  namespace: {{.Values.namespace}}
data:
  BOOTSTRAP_SERVERS: "{{ $bootstrap }}"
  REDIS_HOST: {{ $redis }}
{{ end }}
