{{ $component := .Values.components.decrypterConfig }}
{{ if $component.enabled }}
{{ if .Values.kafkaSecurityConfig.enabled }}

{{ $name := $component.name }}
{{ $config := $component.configuration }}
{{ $kafkaAuth := $config.kafkaAuth }}

apiVersion: v1
kind: Secret
metadata:
  name: {{$name}}
  namespace: {{ .Release.Namespace }}
  labels:
    strmprivacy.io/app: {{$name}}
  annotations:
    strmprivacy.io/version: {{ .Chart.Version }}
data:
  {{- template "kafkaAuthData" $kafkaAuth -}}
{{ end }}
{{ end }}
