{{ $component := .Values.components.webSocket }}
{{ if $component.enabled }}
{{ $name := $component.name }}

{{ $config := $component.configuration }}
{{ $kafkaAuth := $config.kafkaAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{$name}}
  namespace: {{ .Values.namespace }}
  labels:
    strmprivacy.io/app: {{$name}}
  annotations:
    strmprivacy.io/version: {{ .Chart.Version }}
data:
  "kafka.user": {{ $kafkaAuth.user | default "" | b64enc | quote }}
  "kafka.password": {{ $kafkaAuth.password | default "" | b64enc | quote }}
{{ end }}
