{{ $component := .Values.components.webSocket }}
{{ if and $component.enabled .Values.services.clusterIp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: web-socket
  namespace: {{ .Release.Namespace }}
  labels:
    strmprivacy.io/app: web-socket
    strmprivacy.io/version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: envoy-proxy

  selector:
    strmprivacy.io/app: web-socket
{{ end }}
