{{ $config := .Values.globalKafkaSecurityConfig }}
{{ if and $config.enabled $config.saslJaasConfig }}

{{ if ne $config.securityProtocol "SASL_SSL" }}
{{ fail "The kafka securityProtocol must be set to SASL_SSL when specifying a saslJaasConfig" }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: kafka-security-config
  namespace: {{ .Release.Namespace }}
data:
  "sasl.jaas.config": {{ $config.saslJaasConfig | default "" | b64enc | quote }}

{{ end }}
