{{ $component := .Values.components.batchExporterConfig }}
{{ if $component.enabled }}

{{ $name := $component.name }}
{{ $bootstrap := include "kafkaBootstrap" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$name}}
  namespace: {{.Values.namespace}}
data:
  BOOTSTRAP_SERVERS: "{{ $bootstrap }}"
{{ end }}
