{{ $component := .Values.components.streamsAgent }}
{{ if $component.enabled }}
{{ $config := $component.configuration }}
{{ $kafka := .Values.kafka}}
{{ $bootstrap := $kafka.bootstrapServers |
          default (printf "%s-headless.%s.svc.cluster.local:%s" $kafka.fullnameOverride .Values.namespace $kafka.port) }}
{{ $redisSecretName := $config.redisSecret.name | default (printf "%s" .Values.redis.fullnameOverride) }}
{{ $redisSecretKey := $config.redisSecret.key | default "redis-password" }}
{{ $image := eq .Values.license.installationType "SELF_HOSTED" | ternary
(printf "%s/%s/%s/%s:%s" .Values.registry.url .Values.registry.base.prefix .Values.registry.base.path $component.image.name $component.image.version)
(printf "%s/%s:%s" .Values.registry.awsMarketplaceUrl (regexReplaceAll ".+/(.+)$" $component.image.name "${1}") $component.image.version)
}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams-agent
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      strmprivacy.io/app: streams-agent
  template:
    metadata:
      labels:
        strmprivacy.io/app: streams-agent
    spec:
      automountServiceAccountToken: true
      {{ if eq .Values.license.installationType "SELF_HOSTED" }}
      imagePullSecrets:
        - name: strmprivacy-docker-registry
      {{ end }}
      containers:
        - name: streams-agent
          image: {{$image}}
          env:
            {{ include "kafkaSecurityEnvironmentVars" .}}
            {{ include "installationEnvironmentVariables" .}}
            {{ if eq .Values.license.installationType "SELF_HOSTED" }}
            {{ include "selfHostedEnvironmentVariables" .}}
            {{ end }}
            - name: APP_DECRYPTER_NAMESPACE
              value: {{ .Values.namespace }}
            - name: STRM_BOOTSTRAP_SERVERS
              value: {{ $bootstrap }}
            - name: STRM_REDIS_SECRET_NAME
              value: {{ $redisSecretName }}
            - name: STRM_REDIS_SECRET_KEY
              value: {{ $redisSecretKey }}
          {{ if .Values.kafkaSecurityConfig.enabled }}
          volumeMounts:
            - mountPath: /var/truststore
              name: client-truststore
      {{ end }}
      serviceAccountName: streams-agent
      volumes:
        {{ if .Values.kafkaSecurityConfig.enabled }}
        - name: client-truststore
          secret:
            secretName: {{ .Values.kafkaSecurityConfig.sslTruststoreSecretName }}
            optional: false
  {{ end }}

  {{ end }}
