{{ $component := .Values.components.streamsAgent }}
{{ if $component.enabled }}
{{ $name := $component.name }}
{{ $config := $component.configuration }}
{{ $bootstrap := include "kafkaBootstrap" . }}
{{ $redisSecretName := $config.redisSecret.name | default (printf "%s" .Values.redis.fullnameOverride) }}
{{ $redisSecretKey := $config.redisSecret.key | default "redis-password" }}
{{ $data := dict "values" .Values "component" $component }}
{{ $image := include "image" $data }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams-agent
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      strmprivacy.io/app: streams-agent
  template:
    metadata:
      labels:
        strmprivacy.io/app: streams-agent
    spec:
      automountServiceAccountToken: true
      {{ if eq .Values.license.installationType "SELF_HOSTED" }}
      imagePullSecrets:
        - name: strmprivacy-docker-registry
      {{ end }}
      containers:
        - name: streams-agent
          image: {{$image}}
          env:
            {{ include "kafkaSecurityEnvironmentVars" .}}
            {{- include "kafkaCredentialsEnvironmentVars" $data -}}
            {{ include "installationEnvironmentVariables" .}}
            {{ if eq .Values.license.installationType "SELF_HOSTED" }}
            {{ include "selfHostedEnvironmentVariables" .}}
            {{ end }}
            - name: APP_DECRYPTER_NAMESPACE
              value: {{ .Values.namespace }}
            - name: STRM_BOOTSTRAP_SERVERS
              value: {{ $bootstrap }}
            - name: STRM_REDIS_SECRET_NAME
              value: {{ $redisSecretName }}
            - name: STRM_REDIS_SECRET_KEY
              value: {{ $redisSecretKey }}
          volumeMounts:
          {{- template "clientTruststoreVolumeMount" . }}
      serviceAccountName: streams-agent
      volumes:
        {{- template "clientTruststoreVolume" . }}
  {{ end }}
