{{ $component := .Values.components.streamsAgent }}
{{ if $component.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: streams-agent
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if and (contains "AWS_" .Values.license.installationType) (((.Values.marketplace).aws).serviceAccountRoleArn) }}
    eks.amazonaws.com/role-arn: "{{ ((.Values.marketplace).aws).serviceAccountRoleArn }}"
    {{- end }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: streams-agent
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - configmaps
      - deployments
    verbs:
      - list
      - create
      - update
      - patch
      - get
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streams-agent-customers
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: streams-agent
subjects:
  - kind: ServiceAccount
    name: streams-agent
    namespace: {{ .Release.Namespace }}

{{ end }}
