admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: {{ .Values.components.webSocket.configuration.envoy.adminPort }}

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.components.webSocket.configuration.envoy.port }}
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                upgrade_configs:
                  - upgrade_type: websocket
                access_log:
                  - name: envoy.access_loggers.file
                    filter:
                      status_code_filter:
                        comparison:
                          op: GE
                          value:
                            default_value: 500
                            runtime_key: access_log.access_error.status
                    typed_config:
                      "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                      path: /dev/stdout
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "*" ]
                      routes:
                        - match:
                            path: "/"
                            headers:
                              - name: ":method"
                                exact_match: "GET"
                          route:
                            cluster: web_socket
                            prefix_rewrite: "/is-alive"
                        - match:
                            prefix: "/"
                            headers:
                              - name: ":method"
                                exact_match: "GET"
                          route:
                            cluster: web_socket
                http_filters:
                  - name: envoy.filters.http.health_check
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                      pass_through_mode: true
                      headers:
                        - name: ":path"
                          exact_match: "/ready"
                  - name: envoy.filters.http.jwt_authn
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                      providers:
                        accounts-streams-jwt:
                          issuer: 'https://{{ .Values.api.authHost }}/auth/realms/streams'
                          payload_in_metadata: jwt_payload
                          remote_jwks:
                            http_uri:
                              uri: "https://{{ .Values.api.authHost }}/auth/realms/streams/protocol/openid-connect/certs"
                              cluster: {{ .Values.api.authHost }}
                              timeout: 3s
                            cache_duration: 300s
                      rules:
                        - match:
                            path: "/"
                            headers:
                              - name: ":method"
                                exact_match: "GET"
                        - match:
                            prefix: "/"
                            headers:
                              - name: ":method"
                                exact_match: "GET"
                          requires:
                            provider_name: "accounts-streams-jwt"
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                      start_child_span: false
                      suppress_envoy_headers: true
                      upstream_log:
                        - name: envoy.upstream_loggers.file
                          filter:
                            status_code_filter:
                              comparison:
                                op: GE
                                value:
                                  default_value: 500
                                  runtime_key: upstream_log.access_error.status
                          typed_config:
                            "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                            path: /dev/stdout

  clusters:
    - name: web_socket
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      connect_timeout: 2s
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http_protocol_options:
              header_key_format:
                proper_case_words: {}
      load_assignment:
        cluster_name: web_socket
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: {{ .Values.components.webSocket.configuration.appPort }}
    - name: health
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      connect_timeout: 2s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: health
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: {{ .Values.components.webSocket.configuration.appPort }}
    - name: {{ .Values.api.authHost }}
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        connect_timeout: 20s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: {{ .Values.api.authHost }}
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Values.api.authHost }}
                        port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
