admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: {{ .Values.components.eventGateway.configuration.envoy.adminPort }}

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.components.eventGateway.configuration.envoy.port }}
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.file
                    filter:
                      status_code_filter:
                        comparison:
                          op: GE
                          value:
                            default_value: 500
                            runtime_key: access_log.access_error.status
                    typed_config:
                      "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                      path: /dev/stdout
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "*" ]
                      routes:
                        - match:
                            path: "/event"
                            headers:
                              - name: ":method"
                                exact_match: "POST"
                          route:
                            cluster: gateway
                            timeout: 15s
                            retry_policy:
                              retry_on: reset,connect-failure,refused-stream
                              num_retries: 1
                            idle_timeout: 300s
                        - match:
                            path: "/ready"
                            headers:
                              - name: ":method"
                                exact_match: "GET"
                          route:
                            cluster: gateway
                            timeout: 15s
                            retry_policy:
                              retry_on: reset,connect-failure,refused-stream
                              num_retries: 1
                            idle_timeout: 300s
                http_filters:
                  - name: envoy.filters.http.health_check
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                      pass_through_mode: true
                      headers:
                        - name: ":path"
                          exact_match: "/ready"
                  - name: envoy.filters.http.jwt_authn
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                      providers:
                        google-jwt:
                          issuer: 'https://securetoken.google.com/{{ .Values.components.eventGateway.configuration.envoy.jwtAudience }}'
                          audiences:
                            - {{ .Values.components.eventGateway.configuration.envoy.jwtAudience }}
                          forward: true
                          remote_jwks:
                            http_uri:
                              uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
                              cluster: jwt.www.googleapis.com|443
                              timeout: 30s
                            cache_duration: 300s
                      rules:
                        - match:
                            path: "/event"
                            headers:
                              - name: ":method"
                                exact_match: "POST"
                          requires:
                            provider_name: "google-jwt"
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                      start_child_span: false
                      suppress_envoy_headers: true
                      upstream_log:
                        - name: envoy.upstream_loggers.file
                          filter:
                            status_code_filter:
                              comparison:
                                op: GE
                                value:
                                  default_value: 500
                                  runtime_key: upstream_log.access_error.status
                          typed_config:
                            "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                            path: /dev/stdout

  clusters:
    - name: gateway
      type: STATIC
      connect_timeout: 20s
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: gateway
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: {{ .Values.components.eventGateway.configuration.appPort }}
    - name: jwt.www.googleapis.com|443
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      connect_timeout: 20s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: jwt.www.googleapis.com|443
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: www.googleapis.com
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
