{
 "title": "Event Gateway",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m, 2m, 3m, 5m, 10m, 15m, 30m, 1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway req/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(strm_gateway_events_total[$interval]))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (pod) (jvm_info{job=\"event-gateway\"}))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(strm_gateway_timing_bucket[$interval])) by (le))",
     "legendFormat": "99% - Gateway"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(strm_gateway_timing_bucket[$interval])) by (le))",
     "legendFormat": "95% - Gateway"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(strm_gateway_timing_bucket[$interval])) by (le))",
     "legendFormat": "90% - Gateway"
    },
    {
     "expr": "0.001*histogram_quantile(0.99, avg(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"gateway\"}[$interval])) by (le))",
     "legendFormat": "99% - Envoy"
    },
    {
     "expr": "0.001*histogram_quantile(0.95, avg(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"gateway\"}[$interval])) by (le))",
     "legendFormat": "95% - Envoy"
    },
    {
     "expr": "0.001*histogram_quantile(0.90, avg(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"gateway\"}[$interval])) by (le))",
     "legendFormat": "90% - Envoy"
    }
   ]
  },
  {
   "title": "Active streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (topic) (strm_gateway_eventsize_total))"
    }
   ]
  },
  {
   "title": "Rate per schema, status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (schemaid,status) (rate(strm_gateway_events_total[$interval]))",
     "legendFormat": "{{schemaid}} {{status}}"
    }
   ]
  },
  {
   "title": "In flight events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "strm_gateway_inflight", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Encrypter rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (encrypt) (rate(strm_encrypter_total[$interval]))",
     "legendFormat": "{{encrypt}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cache) (caffeine_cache_estimated_size)",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cache) (rate(caffeine_cache_hit_total[$interval]))",
     "legendFormat": "{{cache}} - hit"
    },
    {
     "expr": "sum by (cache) (rate(caffeine_cache_miss_total[$interval]))",
     "legendFormat": "{{cache}} - miss"
    }
   ]
  },
  {
   "title": "Redis creation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(strm_gateway_redischannel_total[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Topic Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (rate(strm_gateway_topicerrors_total[$interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Data rate per schema",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(schemaid) (rate(strm_gateway_eventsize_total[$interval]))",
     "legendFormat": " {{schemaid}}"
    }
   ]
  },
  {
   "title": "Kafka send timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(strm_gateway_kafkatiming_bucket\n[5m])) by (le,result,pod))",
     "legendFormat": "{{pod}} {{result}}"
    }
   ]
  },
  {
   "title": "Envoy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Envoy req/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_external_upstream_rq{envoy_response_code=\"204\",envoy_cluster_name=\"gateway\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Live servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{pod=~\"event-gateway.*\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy)  - sum(envoy_cluster_membership_total))"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "description": "Over all instances.",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_memory_allocated)"
    }
   ]
  },
  {
   "title": "Memory fraction used (allocated / heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "envoy_server_memory_allocated{pod=~\"event-gateway.*\"} / envoy_server_memory_heap_size{pod=~\"event-gateway.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{pod=~\"event-gateway.*\"})-sum(envoy_cluster_membership_healthy{pod=~\"event-gateway.*\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Total Heap Size",
   "type": "stat",
   "description": "Over all instances.",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_external_upstream_rq{envoy_cluster_name=\"gateway\"}[$interval])) by (envoy_response_code,request)",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Envoy data rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"gateway\"}[$interval]))",
     "legendFormat": "gateway"
    }
   ]
  },
  {
   "title": "Latencies (cluster upstream req time)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, avg(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"gateway\"}[$interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"gateway\"}[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, avg(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"gateway\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"gateway\"}[$interval])) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(redis_memory_used_bytes)" }
     ]
    },
    {
     "title": "Commands Executed / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 4, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_commands_processed_total[$interval])"
      }
     ]
    },
    {
     "title": "Hits / Misses per Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 14, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total[$interval])",
       "legendFormat": "hits"
      },
      {
       "expr": "irate(redis_keyspace_misses_total[$interval])",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "avg(redis_memory_used_bytes)", "legendFormat": "used" },
      { "expr": "avg(redis_memory_max_bytes)", "legendFormat": "max" }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(redis_net_input_bytes_total[$interval])",
       "legendFormat": "input"
      },
      {
       "expr": "rate(redis_net_output_bytes_total[$interval])",
       "legendFormat": "output"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys) - sum (redis_db_keys_expiring) ",
       "legendFormat": "not expiring"
      },
      { "expr": "sum (redis_db_keys_expiring) ", "legendFormat": "expiring" }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bytes in",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec_count{topic=~\"stream-.*\",topic!=\"\"}[$interval]))",
       "legendFormat": "Total Incoming Byte Rate"
      }
     ]
    },
    {
     "title": "Kafka storage in use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"data-kafka-.*\"} ) ",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Kafka storage capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) ((kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-kafka-.*\"} - kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-kafka-.*\"}) / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-kafka-.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Bytes out",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec_count{topic=~\"stream-.*\",topic!=\"\"}[$interval]))",
       "legendFormat": "Total Outgoing Byte Rate"
      }
     ]
    },
    {
     "title": "Request Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum by (pod) (kafka_server_request_queue_size)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request Totaltime",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_totaltimems_count{request=~\"Produce|FetchConsumer|FetchFollower\"}) by (request)",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Request Queue time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_requestqueuetimems_count{request=~\"Produce|FetchConsumer|FetchFollower\"}) by (request)",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Request Response send time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_responsesendtimems_count{request=~\"Produce|FetchConsumer|FetchFollower\"}) by (request)",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System & JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Gateway CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (pod,container) (rate(container_cpu_usage_seconds_total{pod=~\"event-gateway.*\",container!=\"\"}[$interval]))",
       "legendFormat": "{{pod}} - {{container}}"
      }
     ]
    },
    {
     "title": "JVM GC Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{pod=~\"event-gateway.*\",container=\"event-gateway\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Node cpu load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "\ninstance:node_cpu_utilisation:rate5m",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg (instance:node_cpu_utilisation:rate5m)",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Envoy CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (pod,container) (rate(container_cpu_usage_seconds_total{pod=~\"event-gateway.*\",container=\"event-gateway-envoy\"}[$interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{pod=~\"event-gateway.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_sum{pod=~\"event-gateway.*\",container=\"event-gateway\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM Thread Count",
     "type": "graph",
     "description": "JVM Thread Count",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{pod=~\"event-gateway.*\",container=\"event-gateway\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Allocated memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "envoy_server_memory_allocated{pod=~\"event-gateway.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "description": "CPU throttling of the Event Gateway pods.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"event-gateway-.*\", container!=\"\"}[$__rate_interval])) by (pod, container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"event-gateway-.*\", container!=\"\"}[$__rate_interval])) by (pod, container)",
       "legendFormat": "{{pod}} {{container}}"
      }
     ]
    }
   ]
  }
 ]
}