{{ $component := .Values.components.eventGateway }}
{{ if $component.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: event-gateway-envoy-config
  namespace: {{ .Release.Namespace }}
  labels:
    strmprivacy.io/app: event-gateway
  annotations:
    strmprivacy.io/version: {{ .Chart.Version }}

data:
  "envoy.yaml": |-
{{ tpl (.Files.Get "resources/event-gateway/envoy.yaml") . | nindent 4 }}

{{end}}
