
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    strmprivacy.io/app: event-gateway
    release: strmprivacy
  name: event-gateway-service-monitor
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
    - port: metrics
  jobLabel: event-gateway
  selector:
    matchLabels:
      strmprivacy.io/app: event-gateway
