{{ $component := .Values.components.eventGateway }}
{{ if $component.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: event-gateway
  namespace: {{ .Values.namespace }}
  labels:
    strmprivacy.io/app: event-gateway
    strmprivacy.io/version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: envoy-proxy
    - name: metrics
      port: 8081
      protocol: TCP
      targetPort: http

  selector:
    strmprivacy.io/app: event-gateway
{{ end }}
