{{ $component := .Values.components.eventGateway }}
{{ if and $component.enabled .Values.services.loadbalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: event-gateway-external
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.services.loadbalancer.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  labels:
    strmprivacy.io/app: event-gateway
    strmprivacy.io/version: {{ .Chart.Version }}
spec:
  type: LoadBalancer
  selector:
    strmprivacy.io/app: event-gateway
  ports:
    - port: 80
      name: http
      targetPort: envoy-proxy
{{ end }}

