{{ if eq .Values.license.installationType "SELF_HOSTED" }}
apiVersion: v1
kind: Secret
metadata:
  name: strmprivacy-docker-registry
  namespace: {{ .Release.Namespace }}
  annotations:
    strmprivacy.io/version: {{ .Chart.Version }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    {{ template "imagePullSecret" . }}
{{ end }}
