apiVersion: v1
kind: Secret
metadata:
  name: strmprivacy-docker-registry
  namespace: {{ .Values.namespace }}
  annotations:
    strmprivacy.io/version: {{ .Chart.Version }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: '{{ template "imagePullSecret" . }}'
