{{- $installationId := .Values.license.installationId | required ".Values.license.installationId is required, please refer to your installation credentials in the console." -}}
{{- $installationClientId := .Values.license.installationClientId | required ".Values.license.installationClientId is required, please refer to your installation credentials in the console." -}}
{{- $installationClientSecret := .Values.license.installationClientSecret | required ".Values.license.installationClientSecret is required, please refer to your installation credentials in the console." -}}

apiVersion: v1
kind: Secret
metadata:
  name: installation-credentials
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  STRM_INSTALLATION_ID: {{ $installationId }}
  STRM_AUTH_CLIENT_ID: {{ $installationClientId }}
  STRM_AUTH_CLIENT_SECRET: {{ $installationClientSecret }}
