apiVersion: v1
kind: Secret
metadata:
  name: installation-credentials
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  STRM_INSTALLATION_ID: {{ .Values.license.installationId }}
  STRM_AUTH_CLIENT_ID: {{ .Values.license.installationClientId }}
  STRM_AUTH_CLIENT_SECRET: {{ .Values.license.installationClientSecret }}
