apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    hallo: "hoi"
    {{- if and (contains "AWS_" .Values.license.installationType) (((.Values.marketplace).aws).serviceAccountRoleArn) }}
    eks.amazonaws.com/role-arn: "{{ ((.Values.marketplace).aws).serviceAccountRoleArn }}"
    {{- end }}
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true

