disableLivenessChecks: true
namespace: strmprivacy

registry:
  url: "europe-west4-docker.pkg.dev"
  base:
    prefix: "stream-machine-development"
    path: "docker-public"

  # Fill out the value below or download a prefilled values.yaml from the Console
  imagePullSecret: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic3RyZWFtLW1hY2hpbmUtZGV2ZWxvcG1lbnQiLAogICJwcml2YXRlX2tleV9pZCI6ICIxYTcyNTc1MmUxYzM2ZWQ4NzZiNTA3MDY2MDAwM2ZkM2YwZmI4YmQ0IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUM1UWY3QnBNTlE1Nzl2XG5jMXN0RUZnOXJlbkxldnBmNEdKelBBbGFBQjB6aHhvbC8vOHRVMTV6QXVOVFFRZjdTRVdSbkJVN0h4QVY0OUtRXG5IYitrcUt1TUU5dGFYaWlBU1BzTGs0MzZOOFVJMHAvaTJyOEZWZGp3MGNsU3kyOHFKbFhyQkFWdHpheDJudFlmXG5FTmM3Z0FHQjAwYzZzNzlhUWV2eDJuUFVaSE5pWmtYRy9uZDB2Z1ZFem16WFZ3UUM5UEg1NUFoS0F1bjdROWZtXG5XUjBhY0dmbWZ2V3Z1dmFCQjU3QVlKQlRWZW1VTXMrQ2NNbWtldW55Y3VEQTBvWWQxOENXRW1Gbm1TNmhLNHBaXG5iUVdURy83R2cxOHFXYmJ3Tk1hcWUrU0hFcGdiYU5xVWEvUUljY1hSeDhIb0ZlRWFKNTJVc2F5Q05iRGdKVzNIXG52YzN5QWxUM0FnTUJBQUVDZ2dFQUJMQ3dJVzJ3OGZoVjd0bXNiQTZ0cTlMTG51QUxVM2RQb0M3VU1lWVgxeXNZXG5iNlQ0UnFNNk13TXBVcm1Jbk82eFZXREkrU3ZpZXBObFUrRUYzdnNRTjE1MWNrSGVwNkVIOTNrbXVLa242bEhFXG5jV0Y3QlJ0cHJRVitiU0hkY0huelZ4V0ppWWdLV1V6dTdTUEZ2cnl2V0dDV2lKR01lNUk4Y3lJWTNTZnFQdDBWXG5Ra3B0YzRPdHBKMERzNzdSZ1lRaWVBMDJtcWRlOVpWZ1BQS3QvemhFbWhmWTVRNnlnanZvR2VhU2Y0aXNNOTB3XG5jSWVDSEJaaWtaMmxuYjF1OVptcFFoM2pLbjlqNnhuM1lxOTdna25HNXNXWi9ZcEM0NW9LQkE0K0E5SnVaa2ZsXG5sOEtjOVlXRnFDYm1xeXVUajZtVXpxajhWU2QyZ2xlVHhQQklpMk9ubVFLQmdRRGNxL1pjaTBrbUxjOVJBTXNoXG42aXpTSU4xeGFWNG1vRWtidWFwaTFGdENkSnhuNUFaTUM1ZHBndmJKVGJHNG9qbE5EdjlLTitBM0xDc1NaeGg0XG42RGg3L1E1OFY4b2N0VUwzSHV1ZFd6eUNNRllSTFZ2S2ovZDJqU3c0UmI5SElHZmJuem9yY01wL3VXZkIwY0RFXG5aZDljOTc0bFEwd1gvR2d3LzVJR3RFOU0vd0tCZ1FEVzZwK3B0VFdLNkJBMWdwUE4wdlBkRXg2czd6STNjckEvXG56OGoyQkpZUG1qWnRKV3pYcUlvc0lWTGMyeDhkaEY5U1lnYVAydVFqcC92SllYY2xHTHpSZkZxS01YWjRYeTV4XG5qbDZHaTJaa3lETE9GaThpaFhZOHRZd1c1ODhSa3p2bVpyNUtWdEtOVXN2K3hQRlFXdEVwcm95M3BoVXpNbDVtXG5TSjV6WEtkZ0NRS0JnQkxQNmlHN2toSGFKK2xjNnZSS05XWDRmVWhVMWp6dXZ5ekk2RGlpcCtFRGRlMzVaM3dHXG5KUE5Pd2VFcGFYUTNDREdFak1qeitINWJtcFJvQzVNTElQMlk5aW90aGNKcXhYbXh2aDVkRDh4OWVHamdlQW5OXG51aWYySXdYdEZFQnBCOUdXUW13L29sTy9KNVJEWUc2ZHpLdnRSdDJBWGpWUlJFU2hGUDdUVWt0YkFvR0FHTTREXG5sNGErbzBXZGVVK1UxNUNkYk1xa0k3bUh4amFLZVJMMlVzNjhzeGhOWjlPRitHNFBaSUNFRzlGK2lkMlpVdHpWXG5mUXo2ZjlNSGtIcWJVY0RGS2poOENxOGl5VW5UQm5BMElMcytHaXV4RVhBbUNJbjIxNUxzbEVnMDhnWllSNE5jXG5PeUJDTk9WMWZmWWxFKzBuYnZRaWNaL05tcGNacGh5RGpUVUliR0VDZ1lFQWszZFk2UjRUS1h5VHVRdnM4RGhiXG4rTVJkT0tqRVphN0VwNmtkZE5kRDBVbjBwM3VLNGRYeGZxRTRjbFQvbXNGOTh0blFoZERoZVBnVzBlcW1iaUNuXG5HaDNEc2tKL3NiemRYMnN6bFpxTUVDSThaUWo3aGhaWG9BaGM3OGNBVjUvbE1BYXBWK0NMS0Z5d2lJdGt0MHprXG5JWXV3SkJOZHpqRCtNT1B1cXZ6UnQ4VT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJpbnN0YWxsYXRpb24tMTEwOTE4MzgzOEBzdHJlYW0tbWFjaGluZS1kZXZlbG9wbWVudC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDQ1OTkxNzUzNDc5MTI1MDc0NDYiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2luc3RhbGxhdGlvbi0xMTA5MTgzODM4JTQwc3RyZWFtLW1hY2hpbmUtZGV2ZWxvcG1lbnQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K"

license:
  # Fill out the values below or download a prefilled values.yaml from the Console
  installationId: "6e2afdf6-6c5c-4984-b353-4ae6f33933ca"
  installationClientId: "ins-6e2afdf66c5c4984b3534ae6f33933ca"
  installationClientSecret: "DSFICgpKHcuoEcThiC72YIZgZJnK2TSU"

api:
  host: "api.dev.strmprivacy.io"
  port: 443
  authUrl: "https://accounts.dev.strmprivacy.io"

kafka:
  enabled: true
  fullnameOverride: "kafka"

redis:
  enabled: true
  fullnameOverride: "redis-hallo"
  global:
    redis:

postgresql:
  enabled: true
  fullnameOverride: "postgres"

components:
  eventGateway:
    enabled: true
    image:
      name: "events/event-gateway"
      version: "v0.57.1"
    replicas: 1
    configuration:
      # Comma separated string
      kafkaBootstrapServers:
      redisHost:
      redisUser:
      redisPassword:

      # Application port, traffic goes via Envoy to the application
      appPort: "8081"
      envoy:
        port: "8080"
        adminPort: "9000"
        jwtAudience:

  webSocket:
    enabled: true
    image:
      name: "events/web-socket"
      version: "v1.16.0"
    name: web-socket
    replicas: 1
    configuration:
      # Comma separated string
      kafkaBootstrapServers:
      # Application port, traffic goes via Envoy to the application
      appPort: "8081"
      envoy:
        port: "8080"
        adminPort: "9000"
        jwtAudience:

  batchJobAgent:
    enabled: true
    image:
      name: "management/entity-agents/batch-jobs-agent"
      version: "v1.12.1"
    name: batch-jobs-agent
    configuration:
      postgres:
        host:
        port:
        user:
        password:
        database:


  batchExportersAgent:
    enabled: true
    name: batch-exporters-agent
    image:
      name: "management/entity-agents/batch-exporters-agent"
      version: "v1.12.0"
    configuration:
      # Comma separated string
      kafkaBootstrapServers:

  streamsAgent:
    enabled: true
    image:
      name: "management/entity-agents/streams-agent"
      version: "v1.14.0"
    configuration:
      redisSecret:
        name:
        key:

  dataConnectorAgent:
    enabled: true
    name: data-connectors-agent
    image:
      name: "management/entity-agents/data-connectors-agent"
      version: "v1.3.0"
    configuration:

  decrypterConfig:
    enabled: true
    kafkaBootstrapServers:
    redisHost:
