#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#mandatory flag --rerun-tasks, otherwise build will be successful second run without making changes
# once we have some more meat in the chart, add `--strict`
helm lint helm --with-subcharts --set registry.imagePullSecret="dummy"
