name: Release Charts

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
         node-version: 16
      - name: Install dependencies
        run: npm i --non-interactive --pure-lockfile
      - name: write tarball
        env:
          STRM_HELM_CHART_SA: ${{ secrets.STRM_HELM_CHART_SA }}
        run: |
          tag_name=$(echo "${GITHUB_REF##*/}" | sed 's/v//g')
          echo "${STRM_HELM_CHART_SA}" > credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
          helm plugin install https://github.com/hayorov/helm-gcs.git
          helm gcs init gs://stream-machine-production-helm-chart/data-plane
          helm repo add helm-bucket gs://stream-machine-production-helm-chart/data-plane
          helm package helm
          npm run semantic-release -- --repository-url "$(git config --get remote.origin.url)"
          helm gcs push strm-${tag_name}.tgz helm-bucket
